language: julia
sudo: false
addons:
  apt:
    packages:
      - texlive
os:
  - linux
  - osx
julia:
  - 0.5
  - nightly
notifications:
  - email: false
after_success:
  - julia -e 'Pkg.clone("https://github.com/MichaelHatherly/Documenter.jl")'
  - julia -e 'cd(Pkg.dir("Nemo")); include(joinpath("doc", "build.jl"))'

