site_name:           Nemo.jl
repo_url:            https://github.com/wbhart/Nemo.jl
site_description:    Nemo
site_author:         William Hart

theme:               readthedocs

pages:
- Getting Started:     index.md

markdown_extensions:
- extra
- tables
- fenced_code
- mdx_math:
    enable_dollar_delimiter: True

docs_dir: 'build'

extra_javascript: ['mathjaxhelper.js', 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']
