site_name:           AbstractAlgebra.jl
repo_url:            https://github.com/Nemocas/AbstractAlgebra.jl
site_description:    AbstractAlgebra
site_author:         William Hart

theme:               readthedocs

pages:
- Getting Started:              index.md
- About AbstractAlgebra:        about.md
- Types in AbstractAlgebra:     types.md
- Parent object constructors:   constructors.md
- Univariate polynomials:       polynomial.md
- Capped relative power series: series.md
- Residue rings:                residue.md             
- Fraction fields:              fraction.md
- Matrices:                     matrix.md
- Integers:                     integer.md
- Rationals:                    rational.md
- Finite fields:                finitefield.md
- Real balls:                   arb.md
- Complex boxes:                acb.md
- Number fields:                numberfield.md
- Permutation groups:           perm.md
- Factorization:                factor.md

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math:
      enable_dollar_delimiter: True

docs_dir: 'build'

extra_javascript: ['mathjaxhelper.js', 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']
